Store server's data schema
RnDAO/tc-dbComm pull request #5
Opened 2022-12-23 19:36 UTC by Behzad-rabiei

2022-12-28 16:58 UTC, mehrdadmms requested changes
The only critical comment is the one regarding connecting to multiple databases. 
Other than that one the rest should be addressed but they're not critical

2022-12-28 16:58 UTC, mehrdadmms commented on __tests__/unit/models/heatMap.model.test.ts
> +
Why did you import moment ?
Please remove it if you don't use it.
Btw, add a rule to eslinter to identify unused imports

2022-12-28 16:58 UTC, mehrdadmms commented on __tests__/unit/models/rawInfo.model.test.ts
> +import moment from "moment";
```suggestion

```

2022-12-28 16:58 UTC, mehrdadmms commented on src/index.ts
> +databaseService.connectToDB('salam')
```suggestion
```
I think this was for development test and should've been removed.

2022-12-28 16:58 UTC, mehrdadmms commented on src/service/database.service.ts
> +
I'm not sure but I think this doesn't satisfy the requirement.
Based on issue definition we should be able to create a database for each discord server.
Using `connectToDB` we can connect to/create a database for a server but how can we switch from one db to another if we want to fetch the information from different servers ? 
Should we disconnect and reconnect again ?

2022-12-28 17:30 UTC, Behzad-rabiei commented on __tests__/unit/models/heatMap.model.test.ts
> +
it was a mistake. 
i will add eslint.

2022-12-30 14:48 UTC, mehrdadmms requested changes
Add lib to .gitignore

2022-12-30 15:55 UTC, mehrdadmms approved these changes

2022-12-30 15:55 UTC, merged